spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: parth
    password: parth
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

logging:
  level:
    root: INFO
    com.ecommerce.order: TRACE
  file:
    name: logs/order-service.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 7

server:
  port: 8083

resilience4j:
  circuitbreaker:
    instances:
      cartService:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        automaticTransitionFromOpenToHalfOpenEnabled: true
        slidingWindowType: count_based



