spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user
    username: parth
    password: parth
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
    com.ecommerce.user: TRACE
  file:
    name: logs/user-service.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 7